# Generated by Django 4.0.2 on 2022-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
